import type { CampaignStep } from '@/contexts/CampaignDraftContext';

export interface CampaignTemplate {
  id: string;
  name: string;
  description: string;
  category: 'simple_connect' | 'engagement' | 'multi_step' | 'conditional' | 'multi_channel';
  complexity: 'beginner' | 'intermediate' | 'advanced';
  channels: string[];
  stepCount: number;
  estimatedDays: number;
  tags: string[];
  steps: Omit<CampaignStep, 'id' | 'order'>[];
  suggestedGoal?: string;
  suggestedAudience?: string;
}

export const TEMPLATE_CATEGORIES = [
  { id: 'simple_connect', name: 'Simple Connect', description: 'Quick connection campaigns', icon: 'UserPlus' },
  { id: 'engagement', name: 'Engagement', description: 'Build relationships through interaction', icon: 'Heart' },
  { id: 'multi_step', name: 'Multi-Step Outreach', description: 'Sequential messaging campaigns', icon: 'ListOrdered' },
  { id: 'conditional', name: 'Conditional Workflows', description: 'Smart if-then automation', icon: 'GitBranch' },
  { id: 'multi_channel', name: 'Multi-Channel ABM', description: 'Coordinated cross-platform campaigns', icon: 'Layers' },
] as const;

export const CAMPAIGN_TEMPLATES: CampaignTemplate[] = [
  {
    id: 'simple-connect',
    name: 'Simple Connect',
    description: 'Send a connection request with an optional personalized note. Perfect for growing your network.',
    category: 'simple_connect',
    complexity: 'beginner',
    channels: ['linkedin_connect'],
    stepCount: 1,
    estimatedDays: 1,
    tags: ['networking', 'quick', 'linkedin'],
    suggestedGoal: 'Grow network with targeted connections',
    suggestedAudience: 'Industry professionals',
    steps: [
      {
        channel: 'linkedin_connect',
        label: 'Connection Request',
        content: '',
        connectionNote: 'Hi {{firstName}}, I came across your profile and was impressed by your work at {{company}}. Would love to connect!',
        delay: 0,
        delayUnit: 'hours',
      },
    ],
  },
  {
    id: 'connect-and-welcome',
    name: 'Connect & Welcome',
    description: 'Send a connection request, then welcome them with a message once they accept.',
    category: 'simple_connect',
    complexity: 'beginner',
    channels: ['linkedin_connect', 'linkedin'],
    stepCount: 2,
    estimatedDays: 3,
    tags: ['networking', 'welcome', 'linkedin'],
    suggestedGoal: 'Build relationships after connecting',
    suggestedAudience: 'New connections',
    steps: [
      {
        channel: 'linkedin_connect',
        label: 'Connection Request',
        content: '',
        connectionNote: 'Hi {{firstName}}, your experience in {{industry}} caught my attention. Would be great to connect!',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'linkedin',
        label: 'Welcome Message',
        content: 'Thanks for connecting, {{firstName}}! I noticed you\'re working on {{topic}}. I\'d love to hear more about your approach. What\'s been your biggest win lately?',
        delay: 1,
        delayUnit: 'days',
        branches: [
          { condition: 'if_connected', action: 'proceed_to_next' },
        ],
      },
    ],
  },
  {
    id: 'profile-engagement',
    name: 'Profile Engagement',
    description: 'Engage with prospects by liking their posts and viewing their profile before connecting.',
    category: 'engagement',
    complexity: 'beginner',
    channels: ['linkedin'],
    stepCount: 3,
    estimatedDays: 5,
    tags: ['engagement', 'warm-up', 'linkedin'],
    suggestedGoal: 'Warm up cold prospects before outreach',
    suggestedAudience: 'Cold leads',
    steps: [
      {
        channel: 'linkedin',
        label: 'Profile View',
        content: '[Action: View profile]',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'linkedin',
        label: 'Like Recent Post',
        content: '[Action: Like their most recent post]',
        delay: 1,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin_connect',
        label: 'Connect with Context',
        content: '',
        connectionNote: 'Hi {{firstName}}, loved your recent post about {{topic}}. Would be great to connect and learn more!',
        delay: 2,
        delayUnit: 'days',
      },
    ],
  },
  {
    id: 'comment-engagement',
    name: 'Thoughtful Commenter',
    description: 'Build visibility by leaving thoughtful comments on prospect posts before reaching out.',
    category: 'engagement',
    complexity: 'intermediate',
    channels: ['linkedin'],
    stepCount: 4,
    estimatedDays: 7,
    tags: ['engagement', 'thought-leadership', 'linkedin'],
    suggestedGoal: 'Build familiarity before sales outreach',
    suggestedAudience: 'Key decision makers',
    steps: [
      {
        channel: 'linkedin',
        label: 'Profile View',
        content: '[Action: View profile and note recent activity]',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'linkedin',
        label: 'Comment on Post #1',
        content: '[Action: Leave thoughtful comment on their content]',
        delay: 2,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin',
        label: 'Comment on Post #2',
        content: '[Action: Engage with another piece of their content]',
        delay: 3,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin_connect',
        label: 'Warm Connection Request',
        content: '',
        connectionNote: 'Hi {{firstName}}, I\'ve been following your insights on {{topic}} - great perspectives! Would love to connect.',
        delay: 2,
        delayUnit: 'days',
      },
    ],
  },
  {
    id: 'linkedin-drip',
    name: 'LinkedIn Drip Campaign',
    description: 'A 5-step LinkedIn message sequence with strategic delays between each touchpoint.',
    category: 'multi_step',
    complexity: 'intermediate',
    channels: ['linkedin'],
    stepCount: 5,
    estimatedDays: 14,
    tags: ['outreach', 'persistent', 'linkedin'],
    suggestedGoal: 'Convert connections to meetings',
    suggestedAudience: 'Existing connections',
    steps: [
      {
        channel: 'linkedin',
        label: 'Initial Outreach',
        content: 'Hi {{firstName}}, I noticed we\'re both in {{industry}}. I\'ve been helping companies like {{company}} with {{value_prop}}. Would you be open to a quick chat?',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'linkedin',
        label: 'Value Add',
        content: 'Hi {{firstName}}, thought you might find this interesting - we just published a case study on how {{similar_company}} achieved {{result}}. Happy to share if useful!',
        delay: 3,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin',
        label: 'Soft Follow-up',
        content: 'Hi {{firstName}}, just circling back. I know you\'re busy - is this something worth exploring, or should I check back another time?',
        delay: 4,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin',
        label: 'Social Proof',
        content: 'Hi {{firstName}}, quick update - we just helped {{reference_company}} in your space solve {{pain_point}}. Given your role, thought this might resonate.',
        delay: 4,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin',
        label: 'Final Touch',
        content: 'Hi {{firstName}}, I\'ll keep this brief - would a 15-min call this week or next work to explore if we can help {{company}}? If timing\'s off, just let me know.',
        delay: 3,
        delayUnit: 'days',
      },
    ],
  },
  {
    id: 'email-sequence',
    name: 'Email Outreach Sequence',
    description: 'A professional 4-email sequence for cold outreach with follow-ups.',
    category: 'multi_step',
    complexity: 'intermediate',
    channels: ['email'],
    stepCount: 4,
    estimatedDays: 10,
    tags: ['email', 'cold-outreach', 'professional'],
    suggestedGoal: 'Book meetings through email',
    suggestedAudience: 'Cold prospects with email',
    steps: [
      {
        channel: 'email',
        label: 'Initial Email',
        subject: 'Quick question about {{company}}',
        content: 'Hi {{firstName}},\n\nI noticed {{company}} is growing in {{industry}}. Many teams at this stage struggle with {{pain_point}}.\n\nWe\'ve helped similar companies achieve {{result}}. Would you be open to a quick call to see if we might be able to help?\n\nBest,\n{{senderName}}',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'email',
        label: 'Follow-up #1',
        subject: 'Re: Quick question about {{company}}',
        content: 'Hi {{firstName}},\n\nJust following up on my previous note. I thought you might find our recent case study interesting - we helped {{similar_company}} increase {{metric}} by {{percentage}}.\n\nWorth a quick chat?\n\nBest,\n{{senderName}}',
        delay: 3,
        delayUnit: 'days',
      },
      {
        channel: 'email',
        label: 'Value-Add Email',
        subject: 'Thought this might help, {{firstName}}',
        content: 'Hi {{firstName}},\n\nI came across this article on {{topic}} and immediately thought of {{company}}. Given your focus on {{their_focus}}, the insights here might be valuable.\n\n[Link]\n\nHappy to discuss how we\'ve applied similar strategies with our clients.\n\nBest,\n{{senderName}}',
        delay: 3,
        delayUnit: 'days',
      },
      {
        channel: 'email',
        label: 'Break-up Email',
        subject: 'Should I close your file?',
        content: 'Hi {{firstName}},\n\nI haven\'t heard back, so I\'m guessing the timing isn\'t right. No worries at all.\n\nIf things change or you\'d like to explore this later, feel free to reach out. I\'ll keep an eye on {{company}}\'s growth!\n\nAll the best,\n{{senderName}}',
        delay: 4,
        delayUnit: 'days',
      },
    ],
  },
  {
    id: 'conditional-connect',
    name: 'Smart Connect Sequence',
    description: 'Automatically adjusts based on whether connection is accepted. If accepted, send welcome message. If not, try alternate approach.',
    category: 'conditional',
    complexity: 'advanced',
    channels: ['linkedin_connect', 'linkedin'],
    stepCount: 4,
    estimatedDays: 10,
    tags: ['smart', 'conditional', 'linkedin'],
    suggestedGoal: 'Maximize connection acceptance and engagement',
    suggestedAudience: 'Target prospects',
    steps: [
      {
        channel: 'linkedin_connect',
        label: 'Initial Connection',
        content: '',
        connectionNote: 'Hi {{firstName}}, your work at {{company}} is impressive. Would love to connect!',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'condition',
        label: 'Check Connection Status',
        content: 'Wait for connection response',
        conditionType: 'if_connected',
        delay: 5,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin',
        label: 'Welcome Message (If Connected)',
        content: 'Thanks for connecting, {{firstName}}! I\'ve been following {{company}}\'s growth in {{industry}}. Would love to learn more about your approach to {{topic}}.',
        delay: 1,
        delayUnit: 'days',
        branches: [
          { condition: 'if_connected', action: 'proceed_to_next' },
        ],
      },
      {
        channel: 'linkedin',
        label: 'Engage with Content (If Not Connected)',
        content: '[Action: Like and comment on their recent posts to build familiarity]',
        delay: 3,
        delayUnit: 'days',
        branches: [
          { condition: 'if_no_response', action: 'proceed_to_next' },
        ],
      },
    ],
  },
  {
    id: 'reply-based-followup',
    name: 'Reply-Based Follow-up',
    description: 'Automatically adjusts follow-up strategy based on whether prospect replies or opens messages.',
    category: 'conditional',
    complexity: 'advanced',
    channels: ['email'],
    stepCount: 5,
    estimatedDays: 14,
    tags: ['smart', 'conditional', 'email', 'automation'],
    suggestedGoal: 'Optimize follow-up based on engagement',
    suggestedAudience: 'Email leads',
    steps: [
      {
        channel: 'email',
        label: 'Initial Email',
        subject: 'Quick question for {{firstName}}',
        content: 'Hi {{firstName}},\n\nI\'ve been researching {{company}} and noticed {{observation}}. We\'ve helped similar companies with {{value_prop}}.\n\nWould a 15-minute chat be worth your time?\n\nBest,\n{{senderName}}',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'condition',
        label: 'Check Reply Status',
        content: 'Wait for reply or track opens',
        conditionType: 'if_replied',
        delay: 3,
        delayUnit: 'days',
      },
      {
        channel: 'email',
        label: 'Opened but No Reply',
        subject: 'Re: Quick question for {{firstName}}',
        content: 'Hi {{firstName}},\n\nI noticed you opened my previous email - hope it was helpful! If you have any questions or want to explore further, I\'m happy to chat.\n\nWould Tuesday or Wednesday work for a quick call?\n\nBest,\n{{senderName}}',
        delay: 2,
        delayUnit: 'days',
        branches: [
          { condition: 'if_opened_not_replied', action: 'proceed_to_next' },
        ],
      },
      {
        channel: 'email',
        label: 'No Open - Try New Subject',
        subject: '{{firstName}}, different approach',
        content: 'Hi {{firstName}},\n\nThought I\'d try a different angle. {{company}} seems like a great fit for what we do.\n\nHere\'s a 2-min video showing how we helped {{similar_company}}: [link]\n\nWorth a look?\n\n{{senderName}}',
        delay: 2,
        delayUnit: 'days',
        branches: [
          { condition: 'if_no_response', action: 'proceed_to_next' },
        ],
      },
      {
        channel: 'email',
        label: 'Final Attempt',
        subject: 'Last try, {{firstName}}',
        content: 'Hi {{firstName}},\n\nI\'ll keep this short - I think we could help {{company}}, but I understand if timing\'s not right.\n\nIf you\'d like to reconnect later, my calendar\'s always open: [link]\n\nBest,\n{{senderName}}',
        delay: 4,
        delayUnit: 'days',
      },
    ],
  },
  {
    id: 'linkedin-email-combo',
    name: 'LinkedIn + Email Combo',
    description: 'Coordinated outreach across LinkedIn and email for maximum touchpoints.',
    category: 'multi_channel',
    complexity: 'intermediate',
    channels: ['linkedin_connect', 'linkedin', 'email'],
    stepCount: 5,
    estimatedDays: 12,
    tags: ['multi-channel', 'linkedin', 'email'],
    suggestedGoal: 'Maximize response rate through multiple channels',
    suggestedAudience: 'High-value prospects',
    steps: [
      {
        channel: 'linkedin_connect',
        label: 'LinkedIn Connection',
        content: '',
        connectionNote: 'Hi {{firstName}}, impressed by {{company}}\'s growth. Would love to connect!',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'email',
        label: 'Email Introduction',
        subject: 'Following up from LinkedIn, {{firstName}}',
        content: 'Hi {{firstName}},\n\nI just sent you a connection request on LinkedIn. Wanted to reach out here as well since I think {{company}} could benefit from {{value_prop}}.\n\nWould you be open to a brief chat?\n\nBest,\n{{senderName}}',
        delay: 1,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin',
        label: 'LinkedIn Message',
        content: 'Hi {{firstName}}, thanks for connecting! I mentioned in my email about {{value_prop}}. Happy to share more if you\'re interested.',
        delay: 2,
        delayUnit: 'days',
        branches: [
          { condition: 'if_connected', action: 'proceed_to_next' },
        ],
      },
      {
        channel: 'email',
        label: 'Email Follow-up',
        subject: 'Re: Following up from LinkedIn, {{firstName}}',
        content: 'Hi {{firstName}},\n\nJust circling back. I\'d love to share how we helped {{similar_company}} achieve {{result}}.\n\nWould a quick 15-min call work this week?\n\nBest,\n{{senderName}}',
        delay: 3,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin',
        label: 'LinkedIn Final Touch',
        content: 'Hi {{firstName}}, last message from me - just wanted to make sure you saw my note about {{value_prop}}. Let me know if worth chatting!',
        delay: 4,
        delayUnit: 'days',
      },
    ],
  },
  {
    id: 'full-abm-sequence',
    name: 'Full ABM Campaign',
    description: 'Enterprise-grade account-based marketing with LinkedIn, email, and phone touchpoints.',
    category: 'multi_channel',
    complexity: 'advanced',
    channels: ['linkedin_connect', 'linkedin', 'email', 'phone'],
    stepCount: 8,
    estimatedDays: 21,
    tags: ['abm', 'enterprise', 'multi-channel', 'comprehensive'],
    suggestedGoal: 'Land enterprise accounts through coordinated outreach',
    suggestedAudience: 'Enterprise decision makers',
    steps: [
      {
        channel: 'linkedin',
        label: 'Research & Engage',
        content: '[Action: View profile, like recent posts]',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'linkedin_connect',
        label: 'Strategic Connection',
        content: '',
        connectionNote: 'Hi {{firstName}}, your leadership at {{company}} in {{industry}} is noteworthy. Would value connecting.',
        delay: 1,
        delayUnit: 'days',
      },
      {
        channel: 'email',
        label: 'Personalized Introduction',
        subject: 'Quick thought for {{company}}, {{firstName}}',
        content: 'Hi {{firstName}},\n\nI\'ve been following {{company}}\'s trajectory in {{industry}}. Given your focus on {{their_initiative}}, I thought you\'d be interested in how we helped {{reference_company}} achieve {{specific_result}}.\n\nWorth 15 minutes to explore?\n\nBest,\n{{senderName}}',
        delay: 2,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin',
        label: 'LinkedIn Follow-up',
        content: 'Hi {{firstName}}, following up on my email about {{value_prop}}. I\'d love to share some specific insights relevant to {{company}}.',
        delay: 3,
        delayUnit: 'days',
      },
      {
        channel: 'phone',
        label: 'Discovery Call Attempt',
        content: 'Call objective: Introduce ourselves, reference email and LinkedIn outreach, propose brief meeting.\n\nScript: "Hi {{firstName}}, this is {{senderName}} from {{ourCompany}}. I\'ve been reaching out about {{value_prop}} - do you have 2 minutes?"',
        delay: 2,
        delayUnit: 'days',
      },
      {
        channel: 'email',
        label: 'Value-Add Email',
        subject: 'Resource for {{company}}: {{industry}} insights',
        content: 'Hi {{firstName}},\n\nI put together a brief analysis of trends in {{industry}} that I thought might be valuable for {{company}}\'s strategy.\n\n[Attached: Industry Brief]\n\nWould love to discuss how these insights apply to your initiatives.\n\nBest,\n{{senderName}}',
        delay: 4,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin',
        label: 'Engagement Touch',
        content: '[Action: Comment thoughtfully on their recent post or share]',
        delay: 3,
        delayUnit: 'days',
      },
      {
        channel: 'email',
        label: 'Executive Summary',
        subject: 'Summary: How we can help {{company}}',
        content: 'Hi {{firstName}},\n\nI wanted to consolidate my outreach with a clear summary:\n\n- We help companies like {{company}} with {{value_prop}}\n- {{reference_company}} saw {{result}} in {{timeframe}}\n- A 20-minute call would help determine if we\'re a fit\n\nI have availability {{suggested_times}}. Would any of those work?\n\nBest,\n{{senderName}}',
        delay: 4,
        delayUnit: 'days',
      },
    ],
  },
  {
    id: 'referral-request',
    name: 'Referral Request',
    description: 'Ask existing connections for introductions to their network.',
    category: 'engagement',
    complexity: 'beginner',
    channels: ['linkedin'],
    stepCount: 2,
    estimatedDays: 5,
    tags: ['referral', 'networking', 'warm'],
    suggestedGoal: 'Get warm introductions to target accounts',
    suggestedAudience: 'Existing connections',
    steps: [
      {
        channel: 'linkedin',
        label: 'Referral Request',
        content: 'Hi {{firstName}}, hope you\'re doing well! I noticed you\'re connected to {{targetName}} at {{targetCompany}}. We\'re doing some interesting work in {{industry}} that might be relevant to them. Would you be comfortable making a quick introduction?',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'linkedin',
        label: 'Thank You & Follow-up',
        content: 'Thanks so much, {{firstName}}! Really appreciate the intro. I\'ll keep you posted on how the conversation goes. Let me know if there\'s ever anything I can do to help you!',
        delay: 3,
        delayUnit: 'days',
        branches: [
          { condition: 'if_replied', action: 'proceed_to_next' },
        ],
      },
    ],
  },
  {
    id: 'event-follow-up',
    name: 'Event Follow-up',
    description: 'Follow up with people you met at conferences, webinars, or networking events.',
    category: 'multi_step',
    complexity: 'beginner',
    channels: ['linkedin_connect', 'email'],
    stepCount: 3,
    estimatedDays: 7,
    tags: ['events', 'networking', 'follow-up'],
    suggestedGoal: 'Convert event connections to meetings',
    suggestedAudience: 'Event attendees',
    steps: [
      {
        channel: 'linkedin_connect',
        label: 'Post-Event Connection',
        content: '',
        connectionNote: 'Hi {{firstName}}, great meeting you at {{eventName}}! Enjoyed our conversation about {{topic}}. Let\'s stay connected.',
        delay: 0,
        delayUnit: 'hours',
      },
      {
        channel: 'email',
        label: 'Email Follow-up',
        subject: 'Great meeting you at {{eventName}}, {{firstName}}',
        content: 'Hi {{firstName}},\n\nIt was great connecting with you at {{eventName}}. I really enjoyed our discussion about {{topic}}.\n\nAs promised, here\'s {{what_you_promised}} that I mentioned.\n\nWould love to continue our conversation - are you free for a coffee chat next week?\n\nBest,\n{{senderName}}',
        delay: 1,
        delayUnit: 'days',
      },
      {
        channel: 'linkedin',
        label: 'LinkedIn Check-in',
        content: 'Hi {{firstName}}, hope you\'re recovering from {{eventName}}! Did you have a chance to look at {{what_you_shared}}? Would love to hear your thoughts and explore how we might collaborate.',
        delay: 4,
        delayUnit: 'days',
      },
    ],
  },
];

export function getTemplatesByCategory(category: string): CampaignTemplate[] {
  return CAMPAIGN_TEMPLATES.filter(t => t.category === category);
}

export function getTemplateById(id: string): CampaignTemplate | undefined {
  return CAMPAIGN_TEMPLATES.find(t => t.id === id);
}

export function searchTemplates(query: string): CampaignTemplate[] {
  const lowerQuery = query.toLowerCase();
  return CAMPAIGN_TEMPLATES.filter(t => 
    t.name.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery) ||
    t.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}
