#!/bin/bash

echo "🚀 Edge Function Deployment Helper"
echo ""
echo "To deploy the updated office365-token-exchange function:"
echo ""
echo "OPTION 1: Via Supabase Dashboard"
echo "--------------------------------"
echo "1. Go to: https://app.supabase.com → Your Project → Edge Functions"
echo "2. Click on 'office365-token-exchange'"
echo "3. Click 'Edit' or 'Redeploy'"
echo "4. Copy ALL the code from: supabase/functions/office365-token-exchange/index.ts"
echo "5. Paste it into the Supabase editor"
echo "6. Click 'Deploy'"
echo ""
echo "OPTION 2: Via Supabase CLI"
echo "--------------------------------"
echo "If you have Supabase CLI installed, run:"
echo "  supabase functions deploy office365-token-exchange"
echo ""
echo "OPTION 3: Check Logs Instead"
echo "--------------------------------"
echo "To see the actual Microsoft error without redeploying:"
echo "1. Go to: https://app.supabase.com → Your Project → Edge Functions"
echo "2. Click on 'office365-token-exchange'"
echo "3. Click the 'Logs' tab"
echo "4. Look for 'Token exchange failed:' errors"
echo "5. Copy the error message and send to agent"
echo ""
